myproject/food/urls.py
from . import views
from django.urls import path



app_name = 'food'
urlpatterns=[
    path('',views.IndexClassView.as_view(), name='index'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('add-item/', views.CreateItem.as_view(), name='add-item'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
   
   
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('food/',include('food.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name ='register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name="logout"),
    path ('profile/', user_views.profilepage, name='profile'),
   
    

]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class item(models.Model):


    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200, default='Default')
    item_desc = models.CharField(max_length=200, default='Default')
    image_url = models.CharField(max_length=500, default ='https://cdn-icons-png.flaticon.com/512/1377/1377194.png')
    item_price = models.IntegerField()


    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk":self.pk})

myproject/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default = 'profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username






# Create your models here.

myproject/food/forms.py
from django import forms
from .models import item

class ItemForm(forms.ModelForm):
    class Meta:
        model = item
        fields = ['item_name', 'item_desc', 'item_price', 'image_url']

myproject/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class RegisterForm(UserCreationForm):
    email = forms.EmailField

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

myproject/food/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import item
from django.template import loader
from .forms import ItemForm
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    
    
    items = item.objects.all()
    context = {
        'items':items,

    }
    return render(request,'food/index.html',context)


class IndexClassView(ListView):
    model = item
    template_name='food/index.html'
    context_object_name='items'





def detail(request,item_id):
    item_id = item.objects.get(pk=item_id)

   
    context = {
        'item': item_id
    }
    return render (request,'food/details.html',context)

class FoodDetail(DetailView):
    model = item
    template_name = 'food/details.html'
    


def add_item(request):

    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/add-item.html', {'form':form})


class CreateItem (CreateView):
    model  = item
    fields = ['item_name','item_desc',"item_price","image_url"]
    template_name = 'food/add-item.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)
    


def update(request,id):

    some_item = item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance = some_item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render (request, 'food/add-item.html', {'item':some_item, 'form':form})


def delete(request, id):
    some_item = item.objects.get(id=id)
    if request.method == 'POST':
        some_item.delete()
        return redirect ('food:index')
    return render(request,'food/item-delete.html', {'item':some_item})


    

myproject/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method =='POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')

    else:
         form = RegisterForm()
    
    return render (request,'users/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

myproject/food/templates/food/add-item.html
{% extends 'food/base.html'%}

{% block body %}

<form method="POST">

    {% csrf_token %}
    {{ form }}


    <button type="submit">Save</button>

</form>




{% endblock %}

myproject/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a href="/food" class="navbar-brand">Food</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="#" class="nav-link">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a href="add-item" class="nav-link">Add item</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Delete item</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">View item</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link" style="padding: 0; border: none; background: none; color: white;">Logout</button>
                        </form>
                    </li>

                    
                    <li>
                        <a href="{% url 'profile' %}" class="nav-link">Profile</a>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">Login</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}

</body>
</html>

myproject/food/templates/food/details.html
{% extends 'food/base.html'%}

{%block body%}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img style="height:300px; width:300px" src="{{item.image_url}}" class= "card">

        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>$ {{object.item_price}}</h3>
            <h4> Created by: {{object.user_name}}</h4>
            <a type="button" class="btn btn-danger" href="{% url 'food:delete' item.id %}">Delete</a>
        </div>
    </div>

</div>






{%endblock%}

myproject/food/templates/food/index.html
{% extends 'food/base.html'%}

<!DOCTYPE html>
<html lang="en">
<head>

    
</head>
<body>

    {% block body %}
         

    {% for item in items  %}



    <div class="row"> 
        <div class="col-md-3 offset-md-2">
            <img class="card" height="100px" width="100px" src="{{item.image_url}}">
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>$ {{item.item_price}}</h6>
            <h6>Created by: {{item.user_name}}</h6>

        </div>
        <div class="col-md-2">
                <a class="btn btn-success" href="{% url 'food:detail' item.id %}" > Details </a>

        </div>
        <hr>
    </div>




    {% endfor %}
    {% endblock %}



   
    
</body>
</html>

myproject/food/templates/food/item-delete.html
{% extends 'food/base.html'%}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <h2>You're about to delete {{item.item_name}}</h2>
    <button type="submit" class="btn btn-danger" >Confirm deletion</button>



</form>



{%endblock%}

myproject/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-titel">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">


                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                             {{field.name}}

                             {{field}}
                            </div>
                        
                        {% endfor %}
                    
                        <button class="btn btn-info" type="submit"> Login </button>
                    
                    
                    </form>

                </div>
            </div>
            
        </div>
    </div>

</div>






{% endblock %}

myproject/users/templates/users/logout.html
<h1>Bye bye</h1>

myproject/users/templates/users/profile.html
<h1>{{ user.username  }}</h1>
<img src="{{ user.profile.image.url }}"  style = "width:300px; height: 300px;">

myproject/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-danger">
                    <div class="card-titel">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">


                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                             {{field.name}}
                             <br>

                             {{field}}
                            </div>
                        
                        {% endfor %}
                            <hr>
                        <button class="btn btn-danger" type="submit"> Sign up </button>
                    
                    
                    </form>

                </div>
            </div>
            
        </div>
    </div>

</div>






{% endblock %}